    <section id="about" class="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Somos una empresa de servicios integrados, donde brindamos servicios multiples y de la mejor calidad a un precio justo en el mercado nacional.</h2>
                    <p class="lead">Eche un vistaso a algunos de nuestros proyectos en nuestra <a target="_blank" href='#portfolio'>Galería</a>.</p>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>