    <aside class="call-to-action bg-primary">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h3>Subscríbase a nuestro boletin.</h3>
                    <a href="#" class="btn btn-lg btn-light">Subscribirse!</a>
                    <a href="#" class="btn btn-lg btn-dark">Solicitar Cotización!</a>
                </div>
            </div>
        </div>
    </aside>