        <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
		<?php echo Html::img('carousel/partenon_beach.jpg','Fachada Hotel Partenon Beach') ?>
 <?php //*<img src="img/carousel/diseno_grafico.jpg" alt="Impresión y Copiado" class="img-responsive"> */ ?>

        </div>
        <div class="item">
		<?php echo Html::img('carousel/fachada_ultramotor.jpg','Fachada Ultramotor') ?>
<?php //*<img src="img/carousel/imprenta_offset.jpg" alt="Imprenta Offset" class="img-responsive">*/ ?>
        </div>
		  
        <div class="item">
		<?php echo Html::img('carousel/fachada_dirgen.jpg','Fachada Ultramotor') ?>
<?php //*<img src="img/carousel/impresion_digital.jpg" alt="Impresión Digital" class="img-responsive">*/ ?>

		</div>
		  
        <div class="item">
		<?php echo Html::img('carousel/fachada_esplendor.jpg','Fachada Esplendor') ?>
<?php //*<img src="img/carousel/impresion_digital.jpg" alt="Impresión Digital" class="img-responsive">*/ ?>

		</div>
	</div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div><!-- /.carousel -->