    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing" >

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <ul class="ch-grid">
					<li>
						<div class="ch-item">				
							<div class="ch-info">
								<div class="ch-info-front ch-img-1"></div>
								<div class="ch-info-back">
									<h3>Mouse</h3>
									<p>by Alexander Shumihin <a href="http://drbl.in/eAoj">View on Dribbble</a></p>
								</div>	
							</div>
						</div>
					</li>
					<li>
						<div class="ch-item">
							<div class="ch-info">
								<div class="ch-info-front ch-img-2"></div>
								<div class="ch-info-back">
									<h3>You</h3>
									<p>by Zoe Ingram <a href="http://drbl.in/eCcV">View on Dribbble</a></p>
								</div>
							</div>
						</div>
					</li>
					<li>
						<div class="ch-item">
							<div class="ch-info">
								<div class="ch-info-front ch-img-3"></div>
								<div class="ch-info-back">
									<h3>Love</h3>
									<p>by Eileen Tjan <a href="http://drbl.in/ewTL">View on Dribbble</a></p>
								</div>
							</div>
						</div>
					</li>
				</ul>
      </div><!-- /.row -->
	
      <div class="row">
        <ul class="ch-grid">
					<li>
						<div class="ch-item">				
							<div class="ch-info">
								<div class="ch-info-front ch-img-1"></div>
								<div class="ch-info-back">
									<h3>Mouse</h3>
									<p>by Alexander Shumihin <a href="http://drbl.in/eAoj">View on Dribbble</a></p>
								</div>	
							</div>
						</div>
					</li>
					<li>
						<div class="ch-item">
							<div class="ch-info">
								<div class="ch-info-front ch-img-2"></div>
								<div class="ch-info-back">
									<h3>You</h3>
									<p>by Zoe Ingram <a href="http://drbl.in/eCcV">View on Dribbble</a></p>
								</div>
							</div>
						</div>
					</li>
					<li>
						<div class="ch-item">
							<div class="ch-info">
								<div class="ch-info-front ch-img-3"></div>
								<div class="ch-info-back">
									<h3>Love</h3>
									<p>by Eileen Tjan <a href="http://drbl.in/ewTL">View on Dribbble</a></p>
								</div>
							</div>
						</div>
					</li>
				</ul>
      </div><!-- /.row -->	        

     

</div>
