      <!-- START THE FEATURETTES -->
      <hr class="featurette-divider">
      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">SmartCopy.com <span class="text-muted">Donde termina tu imaginación, comienza la nuestra...</span></h2>
          <p class="lead">Somos una empresa de productos y servicios publicitarios orientados a servir en su mayor parte al sector empresarial y complementariamente a individuos.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="SmartCopy">
        </div>
       </div>
<hr class="featurette-divider">