<a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
    <nav id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
            <li class="sidebar-brand">
                <a href="#top">VidrieriaLobo.com</a>
            </li>
            <li>
            <?php echo Html::link("#","Inicio") ?>
            </li>
            <li>
            <?php echo Html::link("#about","Nosotros") ?>
            </li>
            <li>
            <?php echo Html::link("#services","Servicios") ?>
            </li>
            <li>
            <?php echo Html::link("#portfolio","Portafolio") ?>
            </li>
            <li>
            <?php echo Html::link("#contact","Contacto") ?>
            </li>
        </ul>
</nav>
