    <section id="services" class="services bg-primary">
        <div class="container">
            <div class="row text-center">
                <div class="col-lg-10 col-lg-offset-1">
                    <h2>Nuestros Servicios</h2>
                    <hr class="small">
                    <div class="row">
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="fa-stack fa-4x">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-glass fa-stack-1x text-primary"></i>
                            </span>
                                <h4>
                                    <strong>Vidriería</strong>
                                </h4>
                                <p>Somos especialistas en vidrio y aluminio, ventanas y fachadas.</p>
                                <?php echo Html::link('productos','Saber Mas...', 'class="btn btn-light"');?>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="fa-stack fa-4x">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-pencil fa-stack-1x text-primary"></i>
                            </span>
                                <h4>
                                    <strong>Maderas</strong>
                                </h4>
                                <p>Fabricamos todo tipo de muebles a la medida de sus necesidades.</p>
                                <?php echo Html::link('productos/verproductos','Saber mas...', 'class="btn btn-light"');?>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="fa-stack fa-4x">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-shield fa-stack-1x text-primary"></i>
                            </span>
                                <h4>
                                    <strong>Hierro</strong>
                                </h4>
                                <p>Estructuras metálicas de todo tipo, balconería y mucho mas...</p>
                                <?php echo Html::link('productos/verproductos','Saber mas...', 'class="btn btn-light"');?>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="fa-stack fa-4x">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-cogs fa-stack-1x text-primary"></i>
                            </span>
                                <h4>
                                    <strong>Otros Servicios</strong>
                                </h4>
                                <p>Mantenimiento y reparación, todo en construcción y mucho mas...</p>
                                <?php echo Html::link('productos/verproductos','Saber mas...', 'class="btn btn-light"');?>
                            </div>
                        </div>
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.col-lg-10 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>