<!-- NAVBAR
================================================== -->
    <div class="navbar-wrapper">
      <div class="container">

        <div class="navbar navbar-inverse navbar-static-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <!-- <a class="navbar-brand" href="#inicio">SmartCopyhn.com</a> -->
                <!-- <a class="navbar-brand" href="#">NBWS</a> -->

                <a href="#inicio"><?php echo Html::img('logo_small.png','SmartCopy.com') ?></a>
            
              </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav" id='top-nav'>
                <li><a href="#inicio">Inicio</a></li>
                <li><a href="#services">Servicios</a></li>
                <li><a href="#about">Nosotros</a></li>
                <li><a href="#portfolio">Portafolio</a></li>
				<li><a href="#contact">Contacto</a></li>
				<li><a href="#test">Test</a></li>                  
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>
